# Generated by Django 4.2.6 on 2024-01-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='invite_reason',
            new_name='instrument',
        ),
    ]
