# Generated by Django 4.2.6 on 2024-01-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0004_reporter_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('publications', models.ManyToManyField(to='pruebas.publication')),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
    ]
