# Generated by Django 4.2.6 on 2024-01-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0005_publication_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='publications',
            field=models.ManyToManyField(related_name='articulos', to='pruebas.publication'),
        ),
    ]
