# Generated by Django 4.2.6 on 2024-01-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0006_alter_articulo_publications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='publications',
            field=models.ManyToManyField(to='pruebas.publication'),
        ),
    ]
