# Generated by Django 4.2.6 on 2024-01-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0009_alter_entry_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='number_of_pimgbacks',
            new_name='number_of_pingbacks',
        ),
    ]
