# Generated by Django 4.2.6 on 2024-03-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0014_country_state_alter_review_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
